-- 250 kosakata Kamus Kei (Veveu Evav), penerjemah: Melkior Labetubun
-- (Elaar Lamagorang). Kategori disimpan di catatan. Lewati bila kata
-- Indonesia-nya sudah ada (ON CONFLICT pada indeks unik lower).
INSERT INTO bahasa_lokal (bahasa_indonesia, bahasa_kei, catatan) VALUES
('aku/saya','ya''a','Kata Ganti'),
('anda/kamu','o','Kata Ganti'),
('dia/ia','i','Kata Ganti'),
('kami/kita','it','Kata Ganti'),
('kalian','im','Kata Ganti'),
('mereka','hiir','Kata Ganti'),
('ini','i''ya','Kata Ganti'),
('itu','i ve','Kata Ganti'),
('sini / di sini','dan i','Kata Ganti'),
('sana / di sana','dan ve','Kata Ganti'),
('apa','a''ka','Kata Tanya'),
('bagaimana','felbe he','Kata Tanya'),
('berapa','hongak be','Kata Tanya'),
('mengapa / kenapa','felbe','Kata Tanya'),
('mana / di mana','na''a be','Kata Tanya'),
('kapan','la fir','Kata Tanya'),
('ke mana','ba bee','Kata Tanya'),
('dari mana','tav dan be','Kata Tanya'),
('siapa','an be i','Kata Tanya'),
('yang mana','an be','Kata Tanya'),
('ajak','her noot','Kata Kerja / Aktivitas Harian'),
('ambil','na''na','Kata Kerja / Aktivitas Harian'),
('baca','naf adir','Kata Kerja / Aktivitas Harian'),
('bangun (tidur)','ba tar','Kata Kerja / Aktivitas Harian'),
('bantu/tolong','tuung','Kata Kerja / Aktivitas Harian'),
('baring/rebah','ntub','Kata Kerja / Aktivitas Harian'),
('bawa','vaar','Kata Kerja / Aktivitas Harian'),
('bayar','vear','Kata Kerja / Aktivitas Harian'),
('belajar','f''adir','Kata Kerja / Aktivitas Harian'),
('beli','fa ha','Kata Kerja / Aktivitas Harian'),
('bersih (membersihkan)','naf kulik','Kata Kerja / Aktivitas Harian'),
('bicara/berbicara','nga rihi/nang rihi','Kata Kerja / Aktivitas Harian'),
('buka','va tun','Kata Kerja / Aktivitas Harian'),
('cari (dia, mereka, kita)','na haar, ra haar, ta haar','Kata Kerja / Aktivitas Harian'),
('cuci (alat makan, pakaian)','vu rik, tof','Kata Kerja / Aktivitas Harian'),
('datang/tiba (dia, mereka)','na dat, ra dat','Kata Kerja / Aktivitas Harian'),
('dengar','denar','Kata Kerja / Aktivitas Harian'),
('diam','moam','Kata Kerja / Aktivitas Harian'),
('duduk','dok','Kata Kerja / Aktivitas Harian'),
('jual','fed','Kata Kerja / Aktivitas Harian'),
('kasih','fiang','Kata Kerja / Aktivitas Harian'),
('keluar','nam eu','Kata Kerja / Aktivitas Harian'),
('kerja','ot''dad','Kata Kerja / Aktivitas Harian'),
('lari','fla','Kata Kerja / Aktivitas Harian'),
('latih/ajar (dia, kita, mereka)','naf adir, taf adir, raf adir','Kata Kerja / Aktivitas Harian'),
('lihat','li''ik','Kata Kerja / Aktivitas Harian'),
('lompat','ohok','Kata Kerja / Aktivitas Harian'),
('lupa','blu fang','Kata Kerja / Aktivitas Harian'),
('makan (dia, kita, mereka)','mu''an, ta''an, ra''an','Kata Kerja / Aktivitas Harian'),
('mandi','luruk','Kata Kerja / Aktivitas Harian'),
('masak','vaik','Kata Kerja / Aktivitas Harian'),
('masuk','ha vaang','Kata Kerja / Aktivitas Harian'),
('matikan','fe dan','Kata Kerja / Aktivitas Harian'),
('mengerti/paham','na kai','Kata Kerja / Aktivitas Harian'),
('minum (dia, kita, mereka)','na nen, ta ten, ra ren','Kata Kerja / Aktivitas Harian'),
('minta','heer','Kata Kerja / Aktivitas Harian'),
('nyalakan','tifar','Kata Kerja / Aktivitas Harian'),
('panggil','vo''o','Kata Kerja / Aktivitas Harian'),
('pegang','ta''ha','Kata Kerja / Aktivitas Harian'),
('pergi (dia, kita, mereka)','na ba, ta ba, ra ba','Kata Kerja / Aktivitas Harian'),
('pikir','fikir','Kata Kerja / Aktivitas Harian'),
('pinjam','f''nen','Kata Kerja / Aktivitas Harian'),
('pulang (dia, kita, mereka)','na ba il, ta ba il, ra ba il','Kata Kerja / Aktivitas Harian'),
('simpan','fak leak','Kata Kerja / Aktivitas Harian'),
('suka','suk mayun','Kata Kerja / Aktivitas Harian'),
('tahu','n''kai','Kata Kerja / Aktivitas Harian'),
('tanya','horak','Kata Kerja / Aktivitas Harian'),
('taruh','fa tub','Kata Kerja / Aktivitas Harian'),
('terima','yo at','Kata Kerja / Aktivitas Harian'),
('tidur','tub kiin','Kata Kerja / Aktivitas Harian'),
('tolak','tuwak','Kata Kerja / Aktivitas Harian'),
('tulis','reng','Kata Kerja / Aktivitas Harian'),
('tunggu','teer','Kata Kerja / Aktivitas Harian'),
('tutup','tuvan','Kata Kerja / Aktivitas Harian'),
('berjalan/jalan','nabati''ma','Kata Kerja / Aktivitas Harian'),
('bagus/baik','bok bok','Kata Sifat & Kondisi'),
('banyak','vang led','Kata Sifat & Kondisi'),
('baru','vait','Kata Sifat & Kondisi'),
('basah','ka bohan','Kata Sifat & Kondisi'),
('benar/betul','ken/tunan','Kata Sifat & Kondisi'),
('berani','baran','Kata Sifat & Kondisi'),
('berat','leman','Kata Sifat & Kondisi'),
('bersih','maliin','Kata Sifat & Kondisi'),
('besar','laai','Kata Sifat & Kondisi'),
('bodoh','burbod','Kata Sifat & Kondisi'),
('capek/lelah','nab re','Kata Sifat & Kondisi'),
('cepat','ken sa','Kata Sifat & Kondisi'),
('dekat','seer','Kata Sifat & Kondisi'),
('dingin','ridin','Kata Sifat & Kondisi'),
('haus (saya, dia, kita, mereka)','u''bro, na bro, tu bro, ra bro','Kata Sifat & Kondisi'),
('hidup','va vain','Kata Sifat & Kondisi'),
('jauh','ro ro','Kata Sifat & Kondisi'),
('jelek/buruk','sisian','Kata Sifat & Kondisi'),
('kecil','kot','Kata Sifat & Kondisi'),
('kenyang','ivun laai','Kata Sifat & Kondisi'),
('kering','adadan','Kata Sifat & Kondisi'),
('kotor','ngu rai','Kata Sifat & Kondisi'),
('lama','mananat','Kata Sifat & Kondisi'),
('lambat/pelan','mang mang','Kata Sifat & Kondisi'),
('lapar','lafar','Kata Sifat & Kondisi'),
('mahal','enan la''ai','Kata Sifat & Kondisi'),
('marah','setan yaf','Kata Sifat & Kondisi'),
('mati','n''mat','Kata Sifat & Kondisi'),
('menangis','roon','Kata Sifat & Kondisi'),
('muda','virun','Kata Sifat & Kondisi'),
('murah','enan kot','Kata Sifat & Kondisi'),
('panas','ngane','Kata Sifat & Kondisi'),
('pintar/cerdas','naf kain','Kata Sifat & Kondisi'),
('rendah','ke baav','Kata Sifat & Kondisi'),
('rindu/kangen','fang nan','Kata Sifat & Kondisi'),
('sakit','suhut','Kata Sifat & Kondisi'),
('salah','sa''sa','Kata Sifat & Kondisi'),
('sedih','mas loen','Kata Sifat & Kondisi'),
('sedikit','dan kot','Kata Sifat & Kondisi'),
('sehat','bok bok','Kata Sifat & Kondisi'),
('senang/bahagia','bok lulin/raan lulin','Kata Sifat & Kondisi'),
('senyum/tawa','been/malit','Kata Sifat & Kondisi'),
('takut','bo bar','Kata Sifat & Kondisi'),
('terdahulu/tua','har u','Kata Sifat & Kondisi'),
('tinggi','karatat','Kata Sifat & Kondisi'),
('adik','war warin','Kata Benda'),
('air','wear','Kata Benda'),
('anak','yan yanat','Kata Benda'),
('angin','neot','Kata Benda'),
('anjing','ya ha','Kata Benda'),
('api','yaf','Kata Benda'),
('ayam','manut','Kata Benda'),
('ayah/bapak (saya, dia, kita, mereka)','ya maang, ya man, ya mad, ya maar','Kata Benda'),
('babi','vav','Kata Benda'),
('badan/tubuh','a tumung','Kata Benda'),
('baju','war','Kata Benda'),
('barang/benda','afa','Kata Benda'),
('batu','vat','Kata Benda'),
('besok','meran','Kata Benda'),
('bintang','naar','Kata Benda'),
('bulan','vuan','Kata Benda'),
('bunga','bung','Kata Benda'),
('daging','dagim','Kata Benda'),
('darah','laar','Kata Benda'),
('darat','na ngan','Kata Benda'),
('gelas/cangkir','soang','Kata Benda'),
('gigi','nifan','Kata Benda'),
('hari','aar','Kata Benda'),
('hati','yatan','Kata Benda'),
('hujan','do''ot','Kata Benda'),
('hutan','yaat','Kata Benda'),
('ibu','renang','Kata Benda'),
('ikan','vu''ut','Kata Benda'),
('jalan','ded','Kata Benda'),
('jantung','vuan','Kata Benda'),
('kakak','yaya''an','Kata Benda'),
('kaki','ye''a','Kata Benda'),
('kampung/desa','ohoi','Kata Benda'),
('kemarin','i dean','Kata Benda'),
('kopi','kof','Kata Benda'),
('kucing','sit','Kata Benda'),
('kursi','kadeer','Kata Benda'),
('laki-laki','ba ran ran','Kata Benda'),
('lampu','damar','Kata Benda'),
('langit','lan/lanit','Kata Benda'),
('laut','tahait','Kata Benda'),
('makanan','bena','Kata Benda'),
('malam','hovan','Kata Benda'),
('manusia/orang','tomat','Kata Benda'),
('mata','madoman','Kata Benda'),
('matahari','leer','Kata Benda'),
('minuman','yen-yen','Kata Benda'),
('mulut (saya, dia)','ngo''eng, ngo''en','Kata Benda'),
('nama','mem','Kata Benda'),
('nasi','ko kat','Kata Benda'),
('orang tua','teteen','Kata Benda'),
('pagi','smer-smer','Kata Benda'),
('pantai','vut roa','Kata Benda'),
('pasir','nguur','Kata Benda'),
('perempuan','vat vat','Kata Benda'),
('pintu','fid','Kata Benda'),
('piring','bingan','Kata Benda'),
('pohon','nuun/voat','Kata Benda'),
('rambut','muur','Kata Benda'),
('rumah','rahan','Kata Benda'),
('sayur','sik siyoor','Kata Benda'),
('sekarang','haran i','Kata Benda'),
('sendok','huur','Kata Benda'),
('siang','ler nafru','Kata Benda'),
('sore','ler wahan','Kata Benda'),
('tahun','yait','Kata Benda'),
('tanah','tanat','Kata Benda'),
('tangan','lim','Kata Benda'),
('teh','teng','Kata Benda'),
('telinga (saya, dia)','arung, a''run','Kata Benda'),
('teman/sahabat','teer/taa','Kata Benda'),
('uang','seeng','Kata Benda'),
('satu','sa','Angka & Penunjuk Jumlah'),
('dua','ru','Angka & Penunjuk Jumlah'),
('tiga','tel','Angka & Penunjuk Jumlah'),
('empat','faak','Angka & Penunjuk Jumlah'),
('lima','lim','Angka & Penunjuk Jumlah'),
('enam','nean','Angka & Penunjuk Jumlah'),
('tujuh','fit','Angka & Penunjuk Jumlah'),
('delapan','wau','Angka & Penunjuk Jumlah'),
('sembilan','siw','Angka & Penunjuk Jumlah'),
('sepuluh','vut','Angka & Penunjuk Jumlah'),
('pertama','ul ya''an','Angka & Penunjuk Jumlah'),
('terakhir','le sus','Angka & Penunjuk Jumlah'),
('semua/seluruh','bes besa','Angka & Penunjuk Jumlah'),
('setengah/separuh','o dan','Angka & Penunjuk Jumlah'),
('habis/kosong','een','Angka & Penunjuk Jumlah'),
('penuh','raan','Angka & Penunjuk Jumlah'),
('apa ini?','afa''ka-i','Frasa Percakapan & Kata Tugas'),
('apa itu?','afa''ka he','Frasa Percakapan & Kata Tugas'),
('apa kabar?','felbe','Frasa Percakapan & Kata Tugas'),
('astaga','he rang','Frasa Percakapan & Kata Tugas'),
('atau','te','Frasa Percakapan & Kata Tugas'),
('belum','hob','Frasa Percakapan & Kata Tugas'),
('betul/benar kah?','tunan dee','Frasa Percakapan & Kata Tugas'),
('dan','hov','Frasa Percakapan & Kata Tugas'),
('dari','tav','Frasa Percakapan & Kata Tugas'),
('dari mana?','tav bee','Frasa Percakapan & Kata Tugas'),
('dengan','hov','Frasa Percakapan & Kata Tugas'),
('di','na''a','Frasa Percakapan & Kata Tugas'),
('halo/hai','wooi','Frasa Percakapan & Kata Tugas'),
('hati-hati','nraan fo bok','Frasa Percakapan & Kata Tugas'),
('iya/ya','o ho','Frasa Percakapan & Kata Tugas'),
('jangan','wehed','Frasa Percakapan & Kata Tugas'),
('jika/kalau','fel','Frasa Percakapan & Kata Tugas'),
('kabar baik','habar bok','Frasa Percakapan & Kata Tugas'),
('karena','natav','Frasa Percakapan & Kata Tugas'),
('ke','ti','Frasa Percakapan & Kata Tugas'),
('lagi','val','Frasa Percakapan & Kata Tugas'),
('maaf','halal','Frasa Percakapan & Kata Tugas'),
('mari/ayo','mi do','Frasa Percakapan & Kata Tugas'),
('mau ke mana?','ba bee','Frasa Percakapan & Kata Tugas'),
('mungkin/bisa jadi','fel ka','Frasa Percakapan & Kata Tugas'),
('permisi','her permis','Frasa Percakapan & Kata Tugas'),
('saja','wat','Frasa Percakapan & Kata Tugas'),
('sampai jumpa','farmehe tas yoatil val','Frasa Percakapan & Kata Tugas'),
('sangat','na li','Frasa Percakapan & Kata Tugas'),
('selamat datang','tabe','Frasa Percakapan & Kata Tugas'),
('selamat malam','tabe ler hovan','Frasa Percakapan & Kata Tugas'),
('selamat pagi','tabe smer-smer','Frasa Percakapan & Kata Tugas'),
('selamat siang','tabe ler nafru','Frasa Percakapan & Kata Tugas'),
('selamat sore','tabe ler wahan','Frasa Percakapan & Kata Tugas'),
('selamat tinggal','tabe ve im','Frasa Percakapan & Kata Tugas'),
('selesai','een rok','Frasa Percakapan & Kata Tugas'),
('silakan duduk','her fo mdok','Frasa Percakapan & Kata Tugas'),
('sudah','rok','Frasa Percakapan & Kata Tugas'),
('terima kasih','tam ma','Frasa Percakapan & Kata Tugas'),
('tetapi','ni rok','Frasa Percakapan & Kata Tugas'),
('tidak/bukan','we ed','Frasa Percakapan & Kata Tugas'),
('untuk','ve','Frasa Percakapan & Kata Tugas')
ON CONFLICT (LOWER(bahasa_indonesia)) DO NOTHING;
